package shop.entities;
// Generated 03/08/2017 12:24:02 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Account generated by hbm2java
 */
public class Account  implements java.io.Serializable {


     private String username;
     private String password;
     private String fullname;
     private String email;
     private Set consumers = new HashSet(0);

    public Account() {
    }

	
    public Account(String username) {
        this.username = username;
    }
    public Account(String username, String password, String fullname, String email, Set consumers) {
       this.username = username;
       this.password = password;
       this.fullname = fullname;
       this.email = email;
       this.consumers = consumers;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getConsumers() {
        return this.consumers;
    }
    
    public void setConsumers(Set consumers) {
        this.consumers = consumers;
    }




}


