package shop.entities;
// Generated 03/08/2017 12:24:02 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {


     private int id;
     private String name;
     private String description;
     private Set products = new HashSet(0);

    public Category() {
    }

	
    public Category(int id) {
        this.id = id;
    }
    public Category(int id, String name, String description, Set products) {
       this.id = id;
       this.name = name;
       this.description = description;
       this.products = products;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getProducts() {
        return this.products;
    }
    
    public void setProducts(Set products) {
        this.products = products;
    }




}


