package shop.entities;
// Generated 03/08/2017 12:24:02 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Order generated by hbm2java
 */
public class Order  implements java.io.Serializable {


     private Integer id;
     private Consumer consumer;
     private Pay pay;
     private Shipping shipping;
     private String number;
     private Date fecha;
     private Set orderdetails = new HashSet(0);

    public Order() {
    }

    public Order(Consumer consumer, Pay pay, Shipping shipping, String number, Date fecha, Set orderdetails) {
       this.consumer = consumer;
       this.pay = pay;
       this.shipping = shipping;
       this.number = number;
       this.fecha = fecha;
       this.orderdetails = orderdetails;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Consumer getConsumer() {
        return this.consumer;
    }
    
    public void setConsumer(Consumer consumer) {
        this.consumer = consumer;
    }
    public Pay getPay() {
        return this.pay;
    }
    
    public void setPay(Pay pay) {
        this.pay = pay;
    }
    public Shipping getShipping() {
        return this.shipping;
    }
    
    public void setShipping(Shipping shipping) {
        this.shipping = shipping;
    }
    public String getNumber() {
        return this.number;
    }
    
    public void setNumber(String number) {
        this.number = number;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getOrderdetails() {
        return this.orderdetails;
    }
    
    public void setOrderdetails(Set orderdetails) {
        this.orderdetails = orderdetails;
    }




}


